apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /tmp/k8s-pv

